### ISSUE TITLE
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/*.png from xml type xml resource ID #

### ISSUE THREAD

**Issue by itabdullah** [cortinico/slidetoact#84] opened 2019-11-04 08:25 UTC
I am trying to apply custom icon for the slider but getting following crash. The resource is available in drawable folder.
```
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/pointing_hand.png from xml type xml resource ID #0x7f0700ab
        at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1243)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2172)
        at android.content.res.Resources.getXml(Resources.java:1221)
        at com.ncorti.slidetoact.SlideToActView.parseVectorDrawableCompat(SlideToActView.kt:296)
2019-11-04 13:30:53.979 com.** E/AndroidRuntime:     at com.ncorti.slidetoact.SlideToActView.<init>(SlideToActView.kt:271)
        at com.ncorti.slidetoact.SlideToActView.<init>(SlideToActView.kt:40)
        at com.ncorti.slidetoact.SlideToActView.<init>(Unknown Source:6)
        	... 40 more
     Caused by: java.io.FileNotFoundException: Corrupt XML binary file
        at android.content.res.AssetManager.nativeOpenXmlAsset(Native Method)
        at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:1009)
        at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1227)
        	... 46 more
```
## My xml:

```
        <com.ncorti.slidetoact.SlideToActView
            android:id="@+id/btn_swipe"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/home_screen"
            android:layout_margin="30dp"
            app:area_margin="0dp"
            app:elevation="8dp"
            app:slider_icon="@drawable/arrow_right"
            app:inner_color="@color/colorAccent"
            app:outer_color="@color/colorPrimary"
            app:slider_height="64dp"
            app:slider_locked="false"
            app:rotate_icon="true"
            app:text="SWIPE TO REFLECT"
            app:text_color="@android:color/white"
            app:text_size="16sp"
            app:text_style="bold" />
```

## Tesing device:
Samsung A30 - Android version: Pie 9

## Library Version:
```    implementation 'com.ncorti:slidetoact:0.7.0' ```

## Full stacktrace:
```
2019-11-04 13:47:16.887 com.** E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.***, PID: 27796
    android.view.InflateException: Binary XML file line #41: Binary XML file line #41: Error inflating class com.ncorti.slidetoact.SlideToActView
    Caused by: android.view.InflateException: Binary XML file line #41: Error inflating class com.ncorti.slidetoact.SlideToActView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:686)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:829)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:905)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
        at com.**.general.HomeFragment.onCreateView(HomeFragment.java:49)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1395)
        at android.app.Activity.performStart(Activity.java:7348)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3147)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7099)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/arrow_right.png from xml type xml resource ID #0x7f07005e
        at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1243)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2172)
        at android.content.res.Resources.getXml(Resources.java:1221)
        at com.ncorti.slidetoact.SlideToActView.parseVectorDrawableCompat(SlideToActView.kt:332)
2019-11-04 13:47:16.888 com.** E/AndroidRuntime:     at com.ncorti.slidetoact.SlideToActView.<init>(SlideToActView.kt:306)
        at com.ncorti.slidetoact.SlideToActView.<init>(SlideToActView.kt:39)
        at com.ncorti.slidetoact.SlideToActView.<init>(Unknown Source:6)
        	... 40 more
     Caused by: java.io.FileNotFoundException: Corrupt XML binary file
        at android.content.res.AssetManager.nativeOpenXmlAsset(Native Method)
        at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:1009)
        at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1227)
        	... 46 more

```
## Gradle:
```
compileSdkVersion 29
    defaultConfig {
        applicationId "com.***.**"
        minSdkVersion 17
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }
```

Please let me know if you need more details.
Thanks for your support.

**Comment by emmelybl** [comment] 2019-11-04 17:05
I have exactly the same problem. I've tried multiple icons and setting but it always crash.
I hope someone have a solution. 
Thanks in advance.

**Comment by cortinico** [comment] 2019-11-04 17:11
Hi @itabdullah @emmelybl 
Can you please provide more details on the drawable that you're using? Are you using a PNG file? Can you please use a vector drawable and confirm that the crash is still happening?

**Comment by emmelybl** [comment] 2019-11-04 18:05
@cortinico Yes, like you said I was using a PNG file, but I used Inkscape to make it into an SVG and it works perfectly now ! Thank you so much !

**Comment by cortinico** [comment] 2019-11-04 18:30
If your issue is solved, can I ask you to close it? Thanks 👍

**Comment by emmelybl** [comment] 2019-11-04 18:33
@cortinico Sorry, it's not me who opened this issue, I just commented, so I don't think I can close it

**Comment by cortinico** [comment] 2019-11-04 22:13
@itabdullah Can you please verify that converting the drawable to Vector Drawable solves this issue?

**Comment by itabdullah** [comment] 2019-11-05 04:15
> Hi @itabdullah @emmelybl
> Can you please provide more details on the drawable that you're using? Are you using a PNG file? Can you please use a vector drawable and confirm that the crash is still happening?

@cortinico thanks. I used a vector image and yes it is now accepting and working fine. Previously I was using a  PNG file.
Please note: I also tried a SVG file but it too caused crash like PNG. So it seems only vector images works with custom slider icon.

**Comment by cortinico** [comment] 2019-11-05 11:33
Yes, that's the intended behavior. Thanks for verifying

**Closed by cortinico** 2019-11-05 11:33 UTC
Labels: incomplete
