### ISSUE TITLE
Is there a loading state for this button? Any workarounds?

### ISSUE THREAD

**Issue by kumzi** [cortinico/slidetoact#213] opened 2022-10-18 18:13 UTC
I need to use this on a task, I'll be performing a web call and I want to animate the drawable within the button (like loading) and then once I receive the response after the webcall, I need to change the icon and color of the button. How that could be achieved using this API?
Do this have a button have a state? Can this be achieved by any other ways ?
Thanks

**Comment by cortinico** [comment] 2022-10-19 17:26
Closing as this is a duplicate of https://github.com/cortinico/slidetoact/issues/116

**Closed by cortinico** 2022-10-19 17:26 UTC
