### ISSUE TITLE
when i add SetCompleteIcon progrmatically display default icon first time and after display customised ICON. 

### ISSUE THREAD

**Issue by kotnisai** [cortinico/slidetoact#133] opened 2020-08-14 08:35 UTC
## What kind of issue is this?

 - [I have two types of icons is display based on status Complete Icon not fixed ] UI Bug. Please provide a Screenshot/Video/GIF of what's the problem. If you need help to record a video you can follow [this guide](https://developer.android.com/studio/command-line/adb.html#screenrecord)

 - [ ] Functional Bug. Please describe the scenario of the bug. Furthermore, please spend the time to write a failing test.

 - [ ] Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

## Details

In case of bug report, please don't forget to include also:
* Library Version.
* Android Version.
* Emulator/Device specs.
* Logs/Crash reports/Stacktraces.
* Example Code/Link to repositories.

**Comment by cortinico** [comment] 2020-08-14 09:05
Please fill in the template correctly: 

Library Version.
Android Version.
Emulator/Device specs.
Logs/Crash reports/Stacktraces.
Example Code/Link to repositories.

**Comment by kotnisai** [comment] 2020-08-16 08:51
> Please fill in the template correctly:
> 
> Library Version.      0.9.0
> Android Version.    4.0
> Emulator/Device specs.
> Logs/Crash reports/Stacktraces.
> Example Code/Link to repositories.

After swipe the button can i show loading icon some time and show success message.

**Comment by cortinico** [comment] 2020-08-19 18:46
I think this issue is a duplicate of https://github.com/cortinico/slidetoact/issues/116
I'm closing it for now and let's follow over the discussion in the other issue.

**Closed by cortinico** 2020-08-19 18:47 UTC
Labels: information needed
